version: 2
project_name: flight-goat-pp-cli
changelog:
  disable: true
builds:
  - id: flight-goat-pp-cli
    main: ./cmd/flight-goat-pp-cli
    binary: flight-goat-pp-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mvanhorn/printing-press-library/library/travel/flight-goat/internal/cli.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
  - id: flight-goat-pp-mcp
    main: ./cmd/flight-goat-pp-mcp
    binary: flight-goat-pp-mcp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: checksums.txt
brews:
  - name: flight-goat-pp-cli
    repository:
      owner: omarshahine
      name: homebrew-tap
    homepage: "https://github.com/omarshahine/flight-goat-pp-cli"
    description: "AeroAPI is a simple, query-based API that gives software developers access to a variety of FlightAware's flight data."
    install: |
      bin.install "flight-goat-pp-cli"
      bin.install "flight-goat-pp-mcp"
