version: 2
project_name: twitter-pp-cli
changelog:
  disable: true
builds:
  - id: twitter-pp-cli
    main: ./cmd/twitter-pp-cli
    binary: twitter-pp-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X twitter-pp-cli/internal/cli.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
  - id: twitter-pp-mcp
    main: ./cmd/twitter-pp-mcp
    binary: twitter-pp-mcp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: checksums.txt
brews:
  - name: twitter-pp-cli
    repository:
      owner: dinakar-sarbada
      name: homebrew-tap
    homepage: "https://github.com/dinakar-sarbada/twitter-pp-cli"
    description: "Twitter OpenAPI(Swagger) specification"
    install: |
      bin.install "twitter-pp-cli"
      bin.install "twitter-pp-mcp"
