// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newBountiesSubmissionsApproveBountyCmd(flags *rootFlags) *cobra.Command {
	var bodyRewardAmount float64
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "approve-bounty <bountyId> <submissionId>",
		Aliases: []string{"create"},
		Short: "Approve a bounty submission",
		Example: "  dub-pp-cli bounties submissions approve-bounty example-value example-value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/bounties/{bountyId}/submissions/{submissionId}/approve"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("bountyId is required\nUsage: %s %s <%s>", cmd.Root().Name(), cmd.CommandPath(), "bountyId"))
			}
			path = replacePathParam(path, "bountyId", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("submissionId is required\nUsage: %s %s <%s>", cmd.Root().Name(), cmd.CommandPath(), "submissionId"))
			}
			path = replacePathParam(path, "submissionId", args[1])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyRewardAmount != 0.0 {
					body["rewardAmount"] = bodyRewardAmount
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping
				filtered := data
				if flags.compact {
					filtered = compactFields(filtered)
				}
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "submissions",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().Float64Var(&bodyRewardAmount, "rewardamount", 0.0, "The reward amount for the performance-based bounty. Applicable if the bounty reward amount is not set.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
