// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newBountiesSubmissionsListBountyCmd(flags *rootFlags) *cobra.Command {
	var flagStatus string
	var flagGroupId string
	var flagPartnerId string
	var flagSortBy string
	var flagSortOrder string
	var flagPage float64
	var flagPageSize float64
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "list-bounty <bountyId>",
		Aliases: []string{"get"},
		Short: "List bounty submissions",
		Example: "  dub-pp-cli bounties submissions list-bounty example-value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/bounties/{bountyId}/submissions"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("bountyId is required\nUsage: %s %s <%s>", cmd.Root().Name(), cmd.CommandPath(), "bountyId"))
			}
			path = replacePathParam(path, "bountyId", args[0])
			data, err := paginatedGet(c, path, map[string]string{
				"status": fmt.Sprintf("%v", flagStatus),
				"groupId": fmt.Sprintf("%v", flagGroupId),
				"partnerId": fmt.Sprintf("%v", flagPartnerId),
				"sortBy": fmt.Sprintf("%v", flagSortBy),
				"sortOrder": fmt.Sprintf("%v", flagSortOrder),
				"page": fmt.Sprintf("%v", flagPage),
				"pageSize": fmt.Sprintf("%v", flagPageSize),
			}, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagStatus, "status", "", "The status of the submissions to list.")
	cmd.Flags().StringVar(&flagGroupId, "groupid", "", "The ID of the group to list submissions for.")
	cmd.Flags().StringVar(&flagPartnerId, "partnerid", "", "The ID of the partner to list submissions for.")
	cmd.Flags().StringVar(&flagSortBy, "sortby", "completedAt", "The field to sort the submissions by.")
	cmd.Flags().StringVar(&flagSortOrder, "sortorder", "asc", "The order to sort the submissions by.")
	cmd.Flags().Float64Var(&flagPage, "page", 0.0, "The page number for pagination.")
	cmd.Flags().Float64Var(&flagPageSize, "pagesize", 100.000000, "The number of items per page.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
