// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newCommissionsListCmd(flags *rootFlags) *cobra.Command {
	var flagType string
	var flagCustomerId string
	var flagPayoutId string
	var flagPartnerId string
	var flagTenantId string
	var flagGroupId string
	var flagInvoiceId string
	var flagStatus string
	var flagSortBy string
	var flagSortOrder string
	var flagInterval string
	var flagStart string
	var flagEnd string
	var flagTimezone string
	var flagEndingBefore string
	var flagStartingAfter string
	var flagPage float64
	var flagPageSize float64
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "list",
		Short: "List all commissions",
		Example: "  dub-pp-cli commissions list",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/commissions"
			data, err := paginatedGet(c, path, map[string]string{
				"type": fmt.Sprintf("%v", flagType),
				"customerId": fmt.Sprintf("%v", flagCustomerId),
				"payoutId": fmt.Sprintf("%v", flagPayoutId),
				"partnerId": fmt.Sprintf("%v", flagPartnerId),
				"tenantId": fmt.Sprintf("%v", flagTenantId),
				"groupId": fmt.Sprintf("%v", flagGroupId),
				"invoiceId": fmt.Sprintf("%v", flagInvoiceId),
				"status": fmt.Sprintf("%v", flagStatus),
				"sortBy": fmt.Sprintf("%v", flagSortBy),
				"sortOrder": fmt.Sprintf("%v", flagSortOrder),
				"interval": fmt.Sprintf("%v", flagInterval),
				"start": fmt.Sprintf("%v", flagStart),
				"end": fmt.Sprintf("%v", flagEnd),
				"timezone": fmt.Sprintf("%v", flagTimezone),
				"endingBefore": fmt.Sprintf("%v", flagEndingBefore),
				"startingAfter": fmt.Sprintf("%v", flagStartingAfter),
				"page": fmt.Sprintf("%v", flagPage),
				"pageSize": fmt.Sprintf("%v", flagPageSize),
			}, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagType, "type", "", "Type")
	cmd.Flags().StringVar(&flagCustomerId, "customerid", "", "Filter the list of commissions by the associated customer.")
	cmd.Flags().StringVar(&flagPayoutId, "payoutid", "", "Filter the list of commissions by the associated payout.")
	cmd.Flags().StringVar(&flagPartnerId, "partnerid", "", "Filter the list of commissions by the associated partner. When specified, takes precedence over `tenantId`.")
	cmd.Flags().StringVar(&flagTenantId, "tenantid", "", "Filter the list of commissions by the associated partner's `tenantId` (their unique ID within your database).")
	cmd.Flags().StringVar(&flagGroupId, "groupid", "", "Filter the list of commissions by the associated partner group.")
	cmd.Flags().StringVar(&flagInvoiceId, "invoiceid", "", "Filter the list of commissions by the associated invoice. Since invoiceId is unique on a per-program basis, this...")
	cmd.Flags().StringVar(&flagStatus, "status", "", "Filter the list of commissions by their corresponding status.")
	cmd.Flags().StringVar(&flagSortBy, "sortby", "createdAt", "The field to sort the list of commissions by.")
	cmd.Flags().StringVar(&flagSortOrder, "sortorder", "desc", "The sort order for the list of commissions.")
	cmd.Flags().StringVar(&flagInterval, "interval", "all", "The interval to retrieve commissions for.")
	cmd.Flags().StringVar(&flagStart, "start", "", "The start date of the date range to filter the commissions by.")
	cmd.Flags().StringVar(&flagEnd, "end", "", "The end date of the date range to filter the commissions by.")
	cmd.Flags().StringVar(&flagTimezone, "timezone", "", "Timezone")
	cmd.Flags().StringVar(&flagEndingBefore, "endingbefore", "", "If specified, the query only searches for results before this cursor. Mutually exclusive with `startingAfter`.")
	cmd.Flags().StringVar(&flagStartingAfter, "startingafter", "", "If specified, the query only searches for results after this cursor. Mutually exclusive with `endingBefore`.")
	cmd.Flags().Float64Var(&flagPage, "page", 0.0, "DEPRECATED. Use `startingAfter` instead.")
	cmd.Flags().Float64Var(&flagPageSize, "pagesize", 100.000000, "The number of items per page.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
