// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newCommissionsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyAmount float64
	var bodyCurrency string
	var bodyModifyAmount float64
	var bodyStatus string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Update a commission",
		Example: "  dub-pp-cli commissions update 550e8400-e29b-41d4-a716-446655440000",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/commissions/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required\nUsage: %s %s <%s>", cmd.Root().Name(), cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAmount != 0.0 {
					body["amount"] = bodyAmount
				}
				if bodyCurrency != "" {
					body["currency"] = bodyCurrency
				}
				if bodyModifyAmount != 0.0 {
					body["modifyAmount"] = bodyModifyAmount
				}
				if bodyStatus != "" {
					body["status"] = bodyStatus
				}
			}
			data, statusCode, err := c.Patch(path, body)
			if err != nil {
				return classifyAPIError(err)
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping
				filtered := data
				if flags.compact {
					filtered = compactFields(filtered)
				}
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "commissions",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().Float64Var(&bodyAmount, "amount", 0.0, "The new absolute amount for the sale. Paid commissions cannot be updated.")
	cmd.Flags().StringVar(&bodyCurrency, "currency", "usd", "The currency of the sale amount to update. Accepts ISO 4217 currency codes.")
	cmd.Flags().Float64Var(&bodyModifyAmount, "modifyamount", 0.0, "Modify the current sale amount: use positive values to increase the amount, negative values to decrease it. Takes...")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "Useful for marking a commission as refunded, duplicate, canceled, or fraudulent. Takes precedence over `amount` and...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
