// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newCustomersGetIdCmd(flags *rootFlags) *cobra.Command {
	var flagIncludeExpandedFields bool

	cmd := &cobra.Command{
		Use:   "get-id <id>",
		Short: "Retrieve a customer",
		Example: "  dub-pp-cli customers get-id 550e8400-e29b-41d4-a716-446655440000",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/customers/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required\nUsage: %s %s <%s>", cmd.Root().Name(), cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			if flagIncludeExpandedFields != false {
				params["includeExpandedFields"] = fmt.Sprintf("%v", flagIncludeExpandedFields)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().BoolVar(&flagIncludeExpandedFields, "includeexpandedfields", false, "Whether to include expanded fields on the customer (`link`, `partner`, `discount`).")

	return cmd
}
