// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newCustomersGetCmd(flags *rootFlags) *cobra.Command {
	var flagEmail string
	var flagExternalId string
	var flagSearch string
	var flagCountry string
	var flagLinkId string
	var flagProgramId string
	var flagPartnerId string
	var flagIncludeExpandedFields bool
	var flagSortBy string
	var flagSortOrder string
	var flagEndingBefore string
	var flagStartingAfter string
	var flagPage float64
	var flagPageSize float64
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "get",
		Aliases: []string{"list"},
		Short: "Retrieve a list of customers",
		Example: "  dub-pp-cli customers get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/customers"
			data, err := paginatedGet(c, path, map[string]string{
				"email": fmt.Sprintf("%v", flagEmail),
				"externalId": fmt.Sprintf("%v", flagExternalId),
				"search": fmt.Sprintf("%v", flagSearch),
				"country": fmt.Sprintf("%v", flagCountry),
				"linkId": fmt.Sprintf("%v", flagLinkId),
				"programId": fmt.Sprintf("%v", flagProgramId),
				"partnerId": fmt.Sprintf("%v", flagPartnerId),
				"includeExpandedFields": fmt.Sprintf("%v", flagIncludeExpandedFields),
				"sortBy": fmt.Sprintf("%v", flagSortBy),
				"sortOrder": fmt.Sprintf("%v", flagSortOrder),
				"endingBefore": fmt.Sprintf("%v", flagEndingBefore),
				"startingAfter": fmt.Sprintf("%v", flagStartingAfter),
				"page": fmt.Sprintf("%v", flagPage),
				"pageSize": fmt.Sprintf("%v", flagPageSize),
			}, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagEmail, "email", "", "A case-sensitive filter on the list based on the customer's `email` field. The value must be a string. Takes...")
	cmd.Flags().StringVar(&flagExternalId, "externalid", "", "A case-sensitive filter on the list based on the customer's `externalId` field. The value must be a string. Takes...")
	cmd.Flags().StringVar(&flagSearch, "search", "", "A search query to filter customers by email, externalId, or name. If `email` or `externalId` is provided, this will...")
	cmd.Flags().StringVar(&flagCountry, "country", "", "A filter on the list based on the customer's `country` field.")
	cmd.Flags().StringVar(&flagLinkId, "linkid", "", "A filter on the list based on the customer's `linkId` field (the referral link ID).")
	cmd.Flags().StringVar(&flagProgramId, "programid", "", "Program ID to filter by.")
	cmd.Flags().StringVar(&flagPartnerId, "partnerid", "", "Partner ID to filter by.")
	cmd.Flags().BoolVar(&flagIncludeExpandedFields, "includeexpandedfields", false, "Whether to include expanded fields on the customer (`link`, `partner`, `discount`).")
	cmd.Flags().StringVar(&flagSortBy, "sortby", "createdAt", "The field to sort the customers by. The default is `createdAt`.")
	cmd.Flags().StringVar(&flagSortOrder, "sortorder", "desc", "The sort order. The default is `desc`.")
	cmd.Flags().StringVar(&flagEndingBefore, "endingbefore", "", "If specified, the query only searches for results before this cursor. Mutually exclusive with `startingAfter`.")
	cmd.Flags().StringVar(&flagStartingAfter, "startingafter", "", "If specified, the query only searches for results after this cursor. Mutually exclusive with `endingBefore`.")
	cmd.Flags().Float64Var(&flagPage, "page", 0.0, "DEPRECATED. Use `startingAfter` instead.")
	cmd.Flags().Float64Var(&flagPageSize, "pagesize", 100.000000, "The number of items per page.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
