// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newDomainsCheckStatusCmd(flags *rootFlags) *cobra.Command {
	var flagDomains string

	cmd := &cobra.Command{
		Use:   "check-status",
		Short: "Check the availability of one or more domains",
		Example: "  dub-pp-cli domains check-status",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/domains/status"
			params := map[string]string{}
			if flagDomains != "" {
				params["domains"] = fmt.Sprintf("%v", flagDomains)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagDomains, "domains", "", "The domains to search. We only support .link domains for now.")
	_ = cmd.MarkFlagRequired("domains")

	return cmd
}
