// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newDomainsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyAppleAppSiteAssociation string
	var bodyArchived bool
	var bodyAssetLinks string
	var bodyExpiredUrl string
	var bodyLogo string
	var bodyNotFoundUrl string
	var bodyPlaceholder string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "update <slug>",
		Short: "Update a domain",
		Example: "  dub-pp-cli domains update example-value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/domains/{slug}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("slug is required\nUsage: %s %s <%s>", cmd.Root().Name(), cmd.CommandPath(), "slug"))
			}
			path = replacePathParam(path, "slug", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAppleAppSiteAssociation != "" {
					body["appleAppSiteAssociation"] = bodyAppleAppSiteAssociation
				}
				if bodyArchived != false {
					body["archived"] = bodyArchived
				}
				if bodyAssetLinks != "" {
					body["assetLinks"] = bodyAssetLinks
				}
				if bodyExpiredUrl != "" {
					body["expiredUrl"] = bodyExpiredUrl
				}
				if bodyLogo != "" {
					body["logo"] = bodyLogo
				}
				if bodyNotFoundUrl != "" {
					body["notFoundUrl"] = bodyNotFoundUrl
				}
				if bodyPlaceholder != "" {
					body["placeholder"] = bodyPlaceholder
				}
			}
			data, statusCode, err := c.Patch(path, body)
			if err != nil {
				return classifyAPIError(err)
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping
				filtered := data
				if flags.compact {
					filtered = compactFields(filtered)
				}
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "domains",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAppleAppSiteAssociation, "appleappsiteassociation", "", "apple-app-site-association configuration file (for deep link support on iOS).")
	cmd.Flags().BoolVar(&bodyArchived, "archived", false, "Whether to archive this domain. `false` will unarchive a previously archived domain.")
	cmd.Flags().StringVar(&bodyAssetLinks, "assetlinks", "", "assetLinks.json configuration file (for deep link support on Android).")
	cmd.Flags().StringVar(&bodyExpiredUrl, "expiredurl", "", "Redirect users to a specific URL when any link under this domain has expired.")
	cmd.Flags().StringVar(&bodyLogo, "logo", "", "The logo of the domain.")
	cmd.Flags().StringVar(&bodyNotFoundUrl, "notfoundurl", "", "Redirect users to a specific URL when a link under this domain doesn't exist.")
	cmd.Flags().StringVar(&bodyPlaceholder, "placeholder", "", "Provide context to your teammates in the link creation modal by showing them an example of a link to be shortened.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
