// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newLinksGetCountCmd(flags *rootFlags) *cobra.Command {
	var flagDomain string
	var flagTagId string
	var flagTagIds string
	var flagTagNames string
	var flagFolderId string
	var flagSearch string
	var flagUserId string
	var flagTenantId string
	var flagShowArchived bool
	var flagWithTags bool
	var flagGroupBy string

	cmd := &cobra.Command{
		Use:   "get-count",
		Short: "Retrieve links count",
		Example: "  dub-pp-cli links get-count",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/links/count"
			params := map[string]string{}
			if flagDomain != "" {
				params["domain"] = fmt.Sprintf("%v", flagDomain)
			}
			if flagTagId != "" {
				params["tagId"] = fmt.Sprintf("%v", flagTagId)
			}
			if flagTagIds != "" {
				params["tagIds"] = fmt.Sprintf("%v", flagTagIds)
			}
			if flagTagNames != "" {
				params["tagNames"] = fmt.Sprintf("%v", flagTagNames)
			}
			if flagFolderId != "" {
				params["folderId"] = fmt.Sprintf("%v", flagFolderId)
			}
			if flagSearch != "" {
				params["search"] = fmt.Sprintf("%v", flagSearch)
			}
			if flagUserId != "" {
				params["userId"] = fmt.Sprintf("%v", flagUserId)
			}
			if flagTenantId != "" {
				params["tenantId"] = fmt.Sprintf("%v", flagTenantId)
			}
			if flagShowArchived != false {
				params["showArchived"] = fmt.Sprintf("%v", flagShowArchived)
			}
			if flagWithTags != false {
				params["withTags"] = fmt.Sprintf("%v", flagWithTags)
			}
			if flagGroupBy != "" {
				params["groupBy"] = fmt.Sprintf("%v", flagGroupBy)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagDomain, "domain", "", "The domain to filter the links by. E.g. `ac.me`. If not provided, all links for the workspace will be returned.")
	cmd.Flags().StringVar(&flagTagId, "tagid", "", "Deprecated: Use `tagIds` instead. The tag ID to filter the links by.")
	cmd.Flags().StringVar(&flagTagIds, "tagids", "", "The tag IDs to filter the links by.")
	cmd.Flags().StringVar(&flagTagNames, "tagnames", "", "The unique name of the tags assigned to the short link (case insensitive).")
	cmd.Flags().StringVar(&flagFolderId, "folderid", "", "The folder ID to filter the links by.")
	cmd.Flags().StringVar(&flagSearch, "search", "", "The search term to filter the links by. The search term will be matched against the short link slug and the...")
	cmd.Flags().StringVar(&flagUserId, "userid", "", "The user ID to filter the links by.")
	cmd.Flags().StringVar(&flagTenantId, "tenantid", "", "The ID of the tenant that created the link inside your system. If set, will only return links for the specified tenant.")
	cmd.Flags().BoolVar(&flagShowArchived, "showarchived", false, "Whether to include archived links in the response. Defaults to `false` if not provided.")
	cmd.Flags().BoolVar(&flagWithTags, "withtags", false, "DEPRECATED. Filter for links that have at least one tag assigned to them.")
	cmd.Flags().StringVar(&flagGroupBy, "groupby", "", "The field to group the links by.")

	return cmd
}
