// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newLinksGetInfoCmd(flags *rootFlags) *cobra.Command {
	var flagDomain string
	var flagKey string
	var flagLinkId string
	var flagExternalId string

	cmd := &cobra.Command{
		Use:   "get-info",
		Short: "Retrieve a link",
		Example: `  dub-pp-cli links get-info --linkid clk_abc123
  dub-pp-cli links get-info --domain dub.sh --key my-link
  dub-pp-cli links get-info --externalid ext_123`,
		PreRunE: func(cmd *cobra.Command, args []string) error {
			linkid, _ := cmd.Flags().GetString("linkid")
			externalid, _ := cmd.Flags().GetString("externalid")
			domain, _ := cmd.Flags().GetString("domain")
			key, _ := cmd.Flags().GetString("key")
			if linkid == "" && externalid == "" && (domain == "" || key == "") {
				return usageErr(fmt.Errorf("at least one identifier required: --linkid, --externalid, or --domain + --key"))
			}
			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/links/info"
			params := map[string]string{}
			if flagDomain != "" {
				params["domain"] = fmt.Sprintf("%v", flagDomain)
			}
			if flagKey != "" {
				params["key"] = fmt.Sprintf("%v", flagKey)
			}
			if flagLinkId != "" {
				params["linkId"] = fmt.Sprintf("%v", flagLinkId)
			}
			if flagExternalId != "" {
				params["externalId"] = fmt.Sprintf("%v", flagExternalId)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagDomain, "domain", "", "Domain")
	cmd.Flags().StringVar(&flagKey, "key", "", "Key")
	cmd.Flags().StringVar(&flagLinkId, "linkid", "", "The unique ID of the short link.")
	cmd.Flags().StringVar(&flagExternalId, "externalid", "", "This is the ID of the link in the your database.")

	return cmd
}
