// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newPartnersListCmd(flags *rootFlags) *cobra.Command {
	var flagGroupId string
	var flagStatus string
	var flagCountry string
	var flagSortBy string
	var flagSortOrder string
	var flagEmail string
	var flagTenantId string
	var flagSearch string
	var flagPage float64
	var flagPageSize float64
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "list",
		Short: "List all partners",
		Example: "  dub-pp-cli partners list",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/partners"
			data, err := paginatedGet(c, path, map[string]string{
				"groupId": fmt.Sprintf("%v", flagGroupId),
				"status": fmt.Sprintf("%v", flagStatus),
				"country": fmt.Sprintf("%v", flagCountry),
				"sortBy": fmt.Sprintf("%v", flagSortBy),
				"sortOrder": fmt.Sprintf("%v", flagSortOrder),
				"email": fmt.Sprintf("%v", flagEmail),
				"tenantId": fmt.Sprintf("%v", flagTenantId),
				"search": fmt.Sprintf("%v", flagSearch),
				"page": fmt.Sprintf("%v", flagPage),
				"pageSize": fmt.Sprintf("%v", flagPageSize),
			}, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagGroupId, "groupid", "", "A filter on the list based on the partner's `groupId` field.")
	cmd.Flags().StringVar(&flagStatus, "status", "", "A filter on the list based on the partner's `status` field.")
	cmd.Flags().StringVar(&flagCountry, "country", "", "A filter on the list based on the partner's `country` field.")
	cmd.Flags().StringVar(&flagSortBy, "sortby", "totalSaleAmount", "The field to sort the partners by. The default is `totalSaleAmount`.")
	cmd.Flags().StringVar(&flagSortOrder, "sortorder", "desc", "The sort order. The default is `desc`.")
	cmd.Flags().StringVar(&flagEmail, "email", "", "Filter the partner list based on the partner's `email`. The value must be a string. Takes precedence over `search`.")
	cmd.Flags().StringVar(&flagTenantId, "tenantid", "", "Filter the partner list based on the partner's `tenantId`. The value must be a string. Takes precedence over `email`...")
	cmd.Flags().StringVar(&flagSearch, "search", "", "A search query to filter partners by ID, name, email, or link.")
	cmd.Flags().Float64Var(&flagPage, "page", 0.0, "The page number for pagination.")
	cmd.Flags().Float64Var(&flagPageSize, "pagesize", 100.000000, "The number of items per page.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
