// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newPartnersRetrieveLinksCmd(flags *rootFlags) *cobra.Command {
	var flagPartnerId string
	var flagTenantId string

	cmd := &cobra.Command{
		Use:   "retrieve-links",
		Short: "Retrieve a partner's links.",
		Example: "  dub-pp-cli partners retrieve-links",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/partners/links"
			params := map[string]string{}
			if flagPartnerId != "" {
				params["partnerId"] = fmt.Sprintf("%v", flagPartnerId)
			}
			if flagTenantId != "" {
				params["tenantId"] = fmt.Sprintf("%v", flagTenantId)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPartnerId, "partnerid", "", "The ID of the partner to create a link for. Will take precedence over `tenantId` if provided.")
	cmd.Flags().StringVar(&flagTenantId, "tenantid", "", "The ID of the partner in your system. If both `partnerId` and `tenantId` are not provided, an error will be thrown.")

	return cmd
}
