// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newPartnersRetrieveAnalyticsCmd(flags *rootFlags) *cobra.Command {
	var flagPartnerId string
	var flagTenantId string
	var flagInterval string
	var flagStart string
	var flagEnd string
	var flagTimezone string
	var flagQuery string
	var flagGroupBy string

	cmd := &cobra.Command{
		Use:   "retrieve-analytics",
		Short: "Retrieve analytics for a partner",
		Example: "  dub-pp-cli partners retrieve-analytics",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/partners/analytics"
			params := map[string]string{}
			if flagPartnerId != "" {
				params["partnerId"] = fmt.Sprintf("%v", flagPartnerId)
			}
			if flagTenantId != "" {
				params["tenantId"] = fmt.Sprintf("%v", flagTenantId)
			}
			if flagInterval != "" {
				params["interval"] = fmt.Sprintf("%v", flagInterval)
			}
			if flagStart != "" {
				params["start"] = fmt.Sprintf("%v", flagStart)
			}
			if flagEnd != "" {
				params["end"] = fmt.Sprintf("%v", flagEnd)
			}
			if flagTimezone != "" {
				params["timezone"] = fmt.Sprintf("%v", flagTimezone)
			}
			if flagQuery != "" {
				params["query"] = fmt.Sprintf("%v", flagQuery)
			}
			if flagGroupBy != "" {
				params["groupBy"] = fmt.Sprintf("%v", flagGroupBy)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPartnerId, "partnerid", "", "The ID of the partner to create a link for. Will take precedence over `tenantId` if provided.")
	cmd.Flags().StringVar(&flagTenantId, "tenantid", "", "The ID of the partner in your system. If both `partnerId` and `tenantId` are not provided, an error will be thrown.")
	cmd.Flags().StringVar(&flagInterval, "interval", "", "The interval to retrieve analytics for. If undefined, defaults to 24h.")
	cmd.Flags().StringVar(&flagStart, "start", "", "The start date and time when to retrieve analytics from. If set, takes precedence over `interval`.")
	cmd.Flags().StringVar(&flagEnd, "end", "", "The end date and time when to retrieve analytics from. If not provided, defaults to the current date. If set along...")
	cmd.Flags().StringVar(&flagTimezone, "timezone", "UTC", "The IANA time zone code for aligning timeseries granularity (e.g. America/New_York). Defaults to UTC.")
	cmd.Flags().StringVar(&flagQuery, "query", "", "Search the events by a custom metadata value. Only available for lead and sale events. Examples:...")
	cmd.Flags().StringVar(&flagGroupBy, "groupby", "count", "The parameter to group the analytics data points by. Defaults to `count` if undefined.")

	return cmd
}
