// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newPayoutsListCmd(flags *rootFlags) *cobra.Command {
	var flagStatus string
	var flagPartnerId string
	var flagTenantId string
	var flagInvoiceId string
	var flagSortBy string
	var flagSortOrder string
	var flagPage float64
	var flagPageSize float64
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "list",
		Short: "List all payouts",
		Example: "  dub-pp-cli payouts list",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/payouts"
			data, err := paginatedGet(c, path, map[string]string{
				"status": fmt.Sprintf("%v", flagStatus),
				"partnerId": fmt.Sprintf("%v", flagPartnerId),
				"tenantId": fmt.Sprintf("%v", flagTenantId),
				"invoiceId": fmt.Sprintf("%v", flagInvoiceId),
				"sortBy": fmt.Sprintf("%v", flagSortBy),
				"sortOrder": fmt.Sprintf("%v", flagSortOrder),
				"page": fmt.Sprintf("%v", flagPage),
				"pageSize": fmt.Sprintf("%v", flagPageSize),
			}, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagStatus, "status", "", "Filter the list of payouts by their corresponding status.")
	cmd.Flags().StringVar(&flagPartnerId, "partnerid", "", "Filter the list of payouts by the associated partner. When specified, takes precedence over `tenantId`.")
	cmd.Flags().StringVar(&flagTenantId, "tenantid", "", "Filter the list of payouts by the associated partner's `tenantId` (their unique ID within your database).")
	cmd.Flags().StringVar(&flagInvoiceId, "invoiceid", "", "Filter the list of payouts by invoice ID (the unique ID of the invoice you receive for each batch payout you process...")
	cmd.Flags().StringVar(&flagSortBy, "sortby", "amount", "The field to sort the list of payouts by.")
	cmd.Flags().StringVar(&flagSortOrder, "sortorder", "desc", "The sort order for the list of payouts.")
	cmd.Flags().Float64Var(&flagPage, "page", 0.0, "The page number for pagination.")
	cmd.Flags().Float64Var(&flagPageSize, "pagesize", 100.000000, "The number of items per page.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
