// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newQrGetQrcodeCmd(flags *rootFlags) *cobra.Command {
	var flagUrl string
	var flagLogo string
	var flagSize float64
	var flagLevel string
	var flagFgColor string
	var flagBgColor string
	var flagHideLogo bool
	var flagMargin float64
	var flagIncludeMargin bool

	cmd := &cobra.Command{
		Use:   "get-qrcode",
		Aliases: []string{"list"},
		Short: "Retrieve a QR code",
		Example: "  dub-pp-cli qr get-qrcode",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/qr"
			params := map[string]string{}
			if flagUrl != "" {
				params["url"] = fmt.Sprintf("%v", flagUrl)
			}
			if flagLogo != "" {
				params["logo"] = fmt.Sprintf("%v", flagLogo)
			}
			if flagSize != 0.0 {
				params["size"] = fmt.Sprintf("%v", flagSize)
			}
			if flagLevel != "" {
				params["level"] = fmt.Sprintf("%v", flagLevel)
			}
			if flagFgColor != "" {
				params["fgColor"] = fmt.Sprintf("%v", flagFgColor)
			}
			if flagBgColor != "" {
				params["bgColor"] = fmt.Sprintf("%v", flagBgColor)
			}
			if flagHideLogo != false {
				params["hideLogo"] = fmt.Sprintf("%v", flagHideLogo)
			}
			if flagMargin != 0.0 {
				params["margin"] = fmt.Sprintf("%v", flagMargin)
			}
			if flagIncludeMargin != false {
				params["includeMargin"] = fmt.Sprintf("%v", flagIncludeMargin)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagUrl, "url", "", "The URL to generate a QR code for.")
	_ = cmd.MarkFlagRequired("url")
	cmd.Flags().StringVar(&flagLogo, "logo", "", "The logo to include in the QR code. Can only be used with a paid plan on Dub.")
	cmd.Flags().Float64Var(&flagSize, "size", 600.000000, "The size of the QR code in pixels. Defaults to `600` if not provided.")
	cmd.Flags().StringVar(&flagLevel, "level", "L", "The level of error correction to use for the QR code. Defaults to `L` if not provided.")
	cmd.Flags().StringVar(&flagFgColor, "fgcolor", "#000000", "The foreground color of the QR code in hex format. Defaults to `#000000` if not provided.")
	cmd.Flags().StringVar(&flagBgColor, "bgcolor", "#FFFFFF", "The background color of the QR code in hex format. Defaults to `#ffffff` if not provided.")
	cmd.Flags().BoolVar(&flagHideLogo, "hidelogo", false, "Whether to hide the logo in the QR code. Can only be used with a paid plan on Dub.")
	cmd.Flags().Float64Var(&flagMargin, "margin", 2.000000, "The size of the margin around the QR code. Defaults to 2 if not provided.")
	cmd.Flags().BoolVar(&flagIncludeMargin, "includemargin", true, "DEPRECATED: Margin is included by default. Use the `margin` prop to customize the margin size.")

	return cmd
}
