// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"text/tabwriter"
	"time"

	"github.com/mvanhorn/CLI-PP-Library/dub-pp-cli/internal/client"
	"github.com/mvanhorn/CLI-PP-Library/dub-pp-cli/internal/config"
	"github.com/spf13/cobra"
)

var version = "0.1.0-dev"

type rootFlags struct {
	asJSON       bool
	compact      bool
	csv          bool
	plain        bool
	quiet        bool
	dryRun       bool
	noCache      bool
	noInput      bool
	yes          bool
	selectFields string
	configPath   string
	timeout      time.Duration
}

// Execute runs the CLI in non-interactive mode: never prompts, all values via flags or stdin.
func Execute() error {
	var flags rootFlags

	rootCmd := &cobra.Command{
		Use:           "dub-pp-cli",
		Short:         "Dub is the modern link attribution platform for short links, conversion tracking, and affiliate programs.",
		SilenceUsage:  true,
		SilenceErrors: true,
		Version:       version,
	}
	rootCmd.SetVersionTemplate("dub-pp-cli {{ .Version }}\n")

	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "json", false, "Output as JSON")
	rootCmd.PersistentFlags().BoolVar(&flags.compact, "compact", false, "Return only key fields (id, name, status, timestamps) for minimal token usage")
	rootCmd.PersistentFlags().BoolVar(&flags.csv, "csv", false, "Output as CSV (table and array responses)")
	rootCmd.PersistentFlags().BoolVar(&flags.plain, "plain", false, "Output as plain tab-separated text")
	rootCmd.PersistentFlags().BoolVar(&flags.quiet, "quiet", false, "Bare output, one value per line")
	rootCmd.PersistentFlags().StringVar(&flags.configPath, "config", "", "Config file path")
	rootCmd.PersistentFlags().DurationVar(&flags.timeout, "timeout", 30*time.Second, "Request timeout")
	rootCmd.PersistentFlags().BoolVar(&flags.dryRun, "dry-run", false, "Show request without sending")
	rootCmd.PersistentFlags().BoolVar(&flags.noCache, "no-cache", false, "Bypass response cache")
	rootCmd.PersistentFlags().BoolVar(&flags.noInput, "no-input", false, "Disable all interactive prompts (for CI/agents)")
	rootCmd.PersistentFlags().StringVar(&flags.selectFields, "select", "", "Comma-separated fields to include in output (e.g. --select id,name,status)")
	rootCmd.PersistentFlags().BoolVar(&flags.yes, "yes", false, "Skip confirmation prompts (for agents and scripts)")
	rootCmd.PersistentFlags().BoolVar(&noColor, "no-color", false, "Disable colored output")
	rootCmd.PersistentFlags().BoolVar(&humanFriendly, "human-friendly", false, "Enable colored output and rich formatting")
	rootCmd.AddCommand(newAnalyticsCmd(&flags)) 
	rootCmd.AddCommand(newBountiesCmd(&flags)) 
	rootCmd.AddCommand(newCommissionsCmd(&flags)) 
	rootCmd.AddCommand(newCustomersCmd(&flags)) 
	rootCmd.AddCommand(newDomainsCmd(&flags)) 
	rootCmd.AddCommand(newEventsCmd(&flags)) 
	rootCmd.AddCommand(newFoldersCmd(&flags)) 
	rootCmd.AddCommand(newLinksCmd(&flags)) 
	rootCmd.AddCommand(newPartnersCmd(&flags)) 
	rootCmd.AddCommand(newPayoutsCmd(&flags)) 
	rootCmd.AddCommand(newQrCmd(&flags)) 
	rootCmd.AddCommand(newTagsCmd(&flags)) 
	rootCmd.AddCommand(newTokensCmd(&flags)) 
	rootCmd.AddCommand(newTrackCmd(&flags)) 
	rootCmd.AddCommand(newDoctorCmd(&flags))
	rootCmd.AddCommand(newAuthCmd(&flags))
	rootCmd.AddCommand(newExportCmd(&flags))
	rootCmd.AddCommand(newImportCmd(&flags))
	rootCmd.AddCommand(newSearchCmd(&flags))
	rootCmd.AddCommand(newSyncCmd(&flags))
	rootCmd.AddCommand(newTailCmd(&flags))
	rootCmd.AddCommand(newCompareCmd(&flags))
	rootCmd.AddCommand(newWorkflowCmd(&flags))
	rootCmd.AddCommand(newStaleCmd(&flags))
	rootCmd.AddCommand(newHealthCmd(&flags))
	rootCmd.AddCommand(newSnapshotCmd(&flags))
	rootCmd.AddCommand(newVersionCliCmd(&flags))

	return rootCmd.Execute()
}

func ExitCode(err error) int {
	var codeErr *cliError
	if As(err, &codeErr) {
		return codeErr.code
	}
	return 1
}

func (f *rootFlags) newClient() (*client.Client, error) {
	cfg, err := config.Load(f.configPath)
	if err != nil {
		return nil, configErr(err)
	}
	c := client.New(cfg, f.timeout)
	c.DryRun = f.dryRun
	c.NoCache = f.noCache
	return c, nil
}

func (f *rootFlags) printJSON(w *cobra.Command, v any) error {
	enc := json.NewEncoder(w.OutOrStdout())
	enc.SetIndent("", "  ")
	return enc.Encode(v)
}

func (f *rootFlags) printTable(w *cobra.Command, headers []string, rows [][]string) error {
	if f.asJSON {
		return fmt.Errorf("use printJSON for JSON output")
	}
	tw := tabwriter.NewWriter(w.OutOrStdout(), 2, 4, 2, ' ', 0)
	header := ""
	for i, h := range headers {
		if i > 0 {
			header += "\t"
		}
		header += h
	}
	fmt.Fprintln(tw, header)
	for _, row := range rows {
		line := ""
		for i, cell := range row {
			if i > 0 {
				line += "\t"
			}
			line += cell
		}
		fmt.Fprintln(tw, line)
	}
	return tw.Flush()
}

func newVersionCliCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:   "version",
		Short: "Print version",
		RunE: func(cmd *cobra.Command, args []string) error {
			if flags.asJSON {
				out := map[string]string{"version": version}
				data, _ := json.Marshal(out)
				return printOutputWithFlags(cmd.OutOrStdout(), json.RawMessage(data), flags)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "dub-pp-cli %s\n", version)
			return nil
		},
	}
}
