// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newTagsGetCmd(flags *rootFlags) *cobra.Command {
	var flagSortBy string
	var flagSortOrder string
	var flagSearch string
	var flagIds string
	var flagPage float64
	var flagPageSize float64
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "get",
		Aliases: []string{"list"},
		Short: "Retrieve a list of tags",
		Example: "  dub-pp-cli tags get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/tags"
			data, err := paginatedGet(c, path, map[string]string{
				"sortBy": fmt.Sprintf("%v", flagSortBy),
				"sortOrder": fmt.Sprintf("%v", flagSortOrder),
				"search": fmt.Sprintf("%v", flagSearch),
				"ids": fmt.Sprintf("%v", flagIds),
				"page": fmt.Sprintf("%v", flagPage),
				"pageSize": fmt.Sprintf("%v", flagPageSize),
			}, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSortBy, "sortby", "name", "The field to sort the tags by.")
	cmd.Flags().StringVar(&flagSortOrder, "sortorder", "asc", "The order to sort the tags by.")
	cmd.Flags().StringVar(&flagSearch, "search", "", "The search term to filter the tags by.")
	cmd.Flags().StringVar(&flagIds, "ids", "", "IDs of tags to filter by.")
	cmd.Flags().Float64Var(&flagPage, "page", 0.0, "The page number for pagination.")
	cmd.Flags().Float64Var(&flagPageSize, "pagesize", 100.000000, "The number of items per page.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
