version: 2
project_name: nasa-images-pp-cli
changelog:
  disable: true
builds:
  - id: nasa-images-pp-cli
    main: ./cmd/nasa-images-pp-cli
    binary: nasa-images-pp-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mvanhorn/printing-press-library/library/media-and-entertainment/nasa-images/internal/cli.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
  - id: nasa-images-pp-mcp
    main: ./cmd/nasa-images-pp-mcp
    binary: nasa-images-pp-mcp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: checksums.txt
brews:
  - name: nasa-images-pp-cli
    repository:
      owner: trevin-chow
      name: homebrew-tap
    homepage: "https://github.com/mvanhorn/printing-press-library"
    description: "Every NASA Image and Video Library endpoint, plus a local SQLite mirror, FTS search, resumable bulk download,..."
    install: |
      bin.install "nasa-images-pp-cli"
      bin.install "nasa-images-pp-mcp"
