// Copyright 2026 tmchow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package store provides local SQLite persistence for dub-pp-cli.
// Uses modernc.org/sqlite (pure Go, no CGO) for zero-dependency cross-compilation.
// FTS5 full-text search indexes are created for searchable content.
package store

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	_ "modernc.org/sqlite"
)

type Store struct {
	db   *sql.DB
	path string
}

func Open(dbPath string) (*Store, error) {
	if err := os.MkdirAll(filepath.Dir(dbPath), 0o755); err != nil {
		return nil, fmt.Errorf("creating db directory: %w", err)
	}

	db, err := sql.Open("sqlite", dbPath+"?_journal_mode=WAL&_synchronous=NORMAL&_busy_timeout=5000&_foreign_keys=ON&_temp_store=MEMORY&_mmap_size=268435456")
	if err != nil {
		return nil, fmt.Errorf("opening database: %w", err)
	}

	db.SetMaxOpenConns(1)

	s := &Store{db: db, path: dbPath}
	if err := s.migrate(); err != nil {
		db.Close()
		return nil, fmt.Errorf("running migrations: %w", err)
	}

	return s, nil
}

func (s *Store) Close() error {
	return s.db.Close()
}

func (s *Store) migrate() error {
	migrations := []string{
		`CREATE TABLE IF NOT EXISTS resources (id TEXT PRIMARY KEY, resource_type TEXT NOT NULL, data JSON NOT NULL, synced_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE INDEX IF NOT EXISTS idx_resources_type ON resources(resource_type)`,
		`CREATE INDEX IF NOT EXISTS idx_resources_synced ON resources(synced_at)`,
		`CREATE TABLE IF NOT EXISTS sync_state (resource_type TEXT PRIMARY KEY, last_cursor TEXT, last_synced_at DATETIME, total_count INTEGER DEFAULT 0)`,
		`CREATE VIRTUAL TABLE IF NOT EXISTS resources_fts USING fts5(id, resource_type, content, tokenize='porter unicode61')`,
		`CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, event_type TEXT NOT NULL DEFAULT "", link_id TEXT DEFAULT "", domain TEXT DEFAULT "", url TEXT DEFAULT "", country TEXT DEFAULT "", city TEXT DEFAULT "", device TEXT DEFAULT "", browser TEXT DEFAULT "", os TEXT DEFAULT "", referer TEXT DEFAULT "", timestamp TEXT NOT NULL DEFAULT "", sale_amount REAL DEFAULT 0, data JSON NOT NULL, synced_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS folders (id TEXT PRIMARY KEY, data JSON NOT NULL, synced_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE VIRTUAL TABLE IF NOT EXISTS folders_fts USING fts5(description, name, content='folders', content_rowid='rowid')`,
		`CREATE TRIGGER IF NOT EXISTS folders_ai AFTER INSERT ON folders BEGIN INSERT INTO folders_fts(rowid, description, name) VALUES (new.rowid, new.description, new.name); END`,
		`CREATE TRIGGER IF NOT EXISTS folders_ad AFTER DELETE ON folders BEGIN INSERT INTO folders_fts(folders_fts, rowid, description, name) VALUES ('delete', old.rowid, old.description, old.name); END`,
		`CREATE TRIGGER IF NOT EXISTS folders_au AFTER UPDATE ON folders BEGIN INSERT INTO folders_fts(folders_fts, rowid, description, name) VALUES ('delete', old.rowid, old.description, old.name); INSERT INTO folders_fts(rowid, description, name) VALUES (new.rowid, new.description, new.name); END`,
		`CREATE TABLE IF NOT EXISTS partners (id TEXT PRIMARY KEY, data JSON NOT NULL, synced_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE VIRTUAL TABLE IF NOT EXISTS partners_fts USING fts5(description, name, content='partners', content_rowid='rowid')`,
		`CREATE TRIGGER IF NOT EXISTS partners_ai AFTER INSERT ON partners BEGIN INSERT INTO partners_fts(rowid, description, name) VALUES (new.rowid, new.description, new.name); END`,
		`CREATE TRIGGER IF NOT EXISTS partners_ad AFTER DELETE ON partners BEGIN INSERT INTO partners_fts(partners_fts, rowid, description, name) VALUES ('delete', old.rowid, old.description, old.name); END`,
		`CREATE TRIGGER IF NOT EXISTS partners_au AFTER UPDATE ON partners BEGIN INSERT INTO partners_fts(partners_fts, rowid, description, name) VALUES ('delete', old.rowid, old.description, old.name); INSERT INTO partners_fts(rowid, description, name) VALUES (new.rowid, new.description, new.name); END`,
		`CREATE TABLE IF NOT EXISTS tokens (id TEXT PRIMARY KEY, data JSON NOT NULL, synced_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS track (id TEXT PRIMARY KEY, data JSON NOT NULL, synced_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS commissions (id TEXT PRIMARY KEY, data JSON NOT NULL, synced_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS domains (id TEXT PRIMARY KEY, data JSON NOT NULL, synced_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS links (id TEXT PRIMARY KEY, domain TEXT NOT NULL DEFAULT "", key TEXT NOT NULL DEFAULT "", url TEXT NOT NULL DEFAULT "", short_link TEXT NOT NULL DEFAULT "", title TEXT DEFAULT "", description TEXT DEFAULT "", archived INTEGER NOT NULL DEFAULT 0, folder_id TEXT DEFAULT "", clicks INTEGER NOT NULL DEFAULT 0, leads INTEGER NOT NULL DEFAULT 0, sales INTEGER NOT NULL DEFAULT 0, sale_amount REAL NOT NULL DEFAULT 0, last_clicked TEXT DEFAULT "", created_at TEXT NOT NULL DEFAULT "", updated_at TEXT NOT NULL DEFAULT "", data JSON NOT NULL, synced_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS payouts (id TEXT PRIMARY KEY, data JSON NOT NULL, synced_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS qr (id TEXT PRIMARY KEY, data JSON NOT NULL, synced_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS tags (id TEXT PRIMARY KEY, data JSON NOT NULL, synced_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS analytics (id TEXT PRIMARY KEY, data JSON NOT NULL, synced_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS analytics_snapshots (id INTEGER PRIMARY KEY AUTOINCREMENT, group_by TEXT NOT NULL, event_type TEXT NOT NULL, period_start TEXT NOT NULL, period_end TEXT NOT NULL, synced_at TEXT NOT NULL, data JSON NOT NULL)`,
		`CREATE INDEX IF NOT EXISTS idx_analytics_group_period ON analytics_snapshots(group_by, period_start, period_end)`,
		`CREATE TABLE IF NOT EXISTS bounties (id TEXT PRIMARY KEY, data JSON NOT NULL, synced_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS submissions (id TEXT PRIMARY KEY, bounties_id TEXT NOT NULL, data JSON NOT NULL, synced_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE INDEX IF NOT EXISTS idx_submissions_bounties_id ON submissions(bounties_id)`,
		`CREATE TABLE IF NOT EXISTS customers (id TEXT PRIMARY KEY, data JSON NOT NULL, synced_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
	}

	for _, m := range migrations {
		if _, err := s.db.Exec(m); err != nil {
			return fmt.Errorf("migration failed: %w", err)
		}
	}
	if err := s.ensureColumns("links", []string{
		`domain TEXT NOT NULL DEFAULT ""`,
		`"key" TEXT NOT NULL DEFAULT ""`,
		`url TEXT NOT NULL DEFAULT ""`,
		`short_link TEXT NOT NULL DEFAULT ""`,
		`title TEXT DEFAULT ""`,
		`description TEXT DEFAULT ""`,
		`archived INTEGER NOT NULL DEFAULT 0`,
		`folder_id TEXT DEFAULT ""`,
		`clicks INTEGER NOT NULL DEFAULT 0`,
		`leads INTEGER NOT NULL DEFAULT 0`,
		`sales INTEGER NOT NULL DEFAULT 0`,
		`sale_amount REAL NOT NULL DEFAULT 0`,
		`last_clicked TEXT DEFAULT ""`,
		`created_at TEXT NOT NULL DEFAULT ""`,
		`updated_at TEXT NOT NULL DEFAULT ""`,
	}); err != nil {
		return err
	}
	if err := s.ensureColumns("events", []string{
		`event_type TEXT NOT NULL DEFAULT ""`,
		`link_id TEXT DEFAULT ""`,
		`domain TEXT DEFAULT ""`,
		`url TEXT DEFAULT ""`,
		`country TEXT DEFAULT ""`,
		`city TEXT DEFAULT ""`,
		`device TEXT DEFAULT ""`,
		`browser TEXT DEFAULT ""`,
		`os TEXT DEFAULT ""`,
		`referer TEXT DEFAULT ""`,
		`timestamp TEXT NOT NULL DEFAULT ""`,
		`sale_amount REAL DEFAULT 0`,
	}); err != nil {
		return err
	}
	for _, m := range []string{
		`CREATE INDEX IF NOT EXISTS idx_links_domain ON links(domain)`,
		`CREATE INDEX IF NOT EXISTS idx_links_folder_id ON links(folder_id)`,
		`CREATE INDEX IF NOT EXISTS idx_links_created_at ON links(created_at)`,
		`CREATE INDEX IF NOT EXISTS idx_links_clicks ON links(clicks)`,
		`CREATE INDEX IF NOT EXISTS idx_events_link_id ON events(link_id)`,
		`CREATE INDEX IF NOT EXISTS idx_events_event_type ON events(event_type)`,
		`CREATE INDEX IF NOT EXISTS idx_events_timestamp ON events(timestamp)`,
	} {
		if _, err := s.db.Exec(m); err != nil {
			return fmt.Errorf("migration failed: %w", err)
		}
	}
	return s.ensureLinksFTS()
}

func (s *Store) ensureColumns(table string, defs []string) error {
	for _, def := range defs {
		if _, err := s.db.Exec(fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s", table, def)); err != nil && !strings.Contains(strings.ToLower(err.Error()), "duplicate column name") {
			return fmt.Errorf("altering %s: %w", table, err)
		}
	}
	return nil
}

func (s *Store) ensureLinksFTS() error {
	var sqlDef string
	err := s.db.QueryRow(`SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'links_fts'`).Scan(&sqlDef)
	rebuild := err == sql.ErrNoRows || !strings.Contains(strings.ToLower(sqlDef), "url") || !strings.Contains(strings.ToLower(sqlDef), "key")
	if err != nil && err != sql.ErrNoRows {
		return fmt.Errorf("inspecting links_fts: %w", err)
	}
	stmts := []string{
		`DROP TRIGGER IF EXISTS links_ai`,
		`DROP TRIGGER IF EXISTS links_ad`,
		`DROP TRIGGER IF EXISTS links_au`,
	}
	if rebuild {
		stmts = append(stmts,
			`DROP TABLE IF EXISTS links_fts`,
			`CREATE VIRTUAL TABLE IF NOT EXISTS links_fts USING fts5(
				url, key, title, description,
				content=links, content_rowid=rowid,
				tokenize="porter unicode61"
			)`,
		)
	}
	stmts = append(stmts,
		`CREATE TRIGGER IF NOT EXISTS links_ai AFTER INSERT ON links BEGIN
			INSERT INTO links_fts(rowid, url, key, title, description)
			VALUES (new.rowid, new.url, new.key, new.title, new.description);
		END`,
		`CREATE TRIGGER IF NOT EXISTS links_ad AFTER DELETE ON links BEGIN
			INSERT INTO links_fts(links_fts, rowid, url, key, title, description)
			VALUES ('delete', old.rowid, old.url, old.key, old.title, old.description);
		END`,
		`CREATE TRIGGER IF NOT EXISTS links_au AFTER UPDATE ON links BEGIN
			INSERT INTO links_fts(links_fts, rowid, url, key, title, description)
			VALUES ('delete', old.rowid, old.url, old.key, old.title, old.description);
			INSERT INTO links_fts(rowid, url, key, title, description)
			VALUES (new.rowid, new.url, new.key, new.title, new.description);
		END`,
	)
	for _, stmt := range stmts {
		if _, err := s.db.Exec(stmt); err != nil {
			return fmt.Errorf("links FTS migration failed: %w", err)
		}
	}
	if rebuild {
		if _, err := s.db.Exec(`INSERT INTO links_fts(links_fts) VALUES ('rebuild')`); err != nil {
			return fmt.Errorf("rebuilding links FTS: %w", err)
		}
	}
	return nil
}

func (s *Store) upsertGenericResourceTx(tx *sql.Tx, resourceType, id string, data json.RawMessage) error {
	_, err := tx.Exec(
		`INSERT INTO resources (id, resource_type, data, synced_at, updated_at)
		 VALUES (?, ?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET data = excluded.data, synced_at = excluded.synced_at, updated_at = excluded.updated_at`,
		id, resourceType, string(data), time.Now(), time.Now(),
	)
	if err != nil {
		return err
	}

	_, err = tx.Exec(`DELETE FROM resources_fts WHERE id = ?`, id)
	if err != nil {
		fmt.Fprintf(os.Stderr, "warning: FTS index cleanup failed: %v\n", err)
	}

	_, err = tx.Exec(
		`INSERT INTO resources_fts (id, resource_type, content)
		 VALUES (?, ?, ?)`,
		id, resourceType, string(data),
	)
	if err != nil {
		// FTS insert failure is non-fatal
		fmt.Fprintf(os.Stderr, "warning: FTS index update failed: %v\n", err)
	}

	return nil
}

func (s *Store) withTx(fn func(*sql.Tx) error) error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if err := fn(tx); err != nil {
		return err
	}
	return tx.Commit()
}

func (s *Store) Upsert(resourceType, id string, data json.RawMessage) error {
	switch resourceType {
	case "links":
		return s.UpsertLink(data)
	case "events":
		return s.UpsertEvent(data)
	case "submissions":
		return s.UpsertSubmissions(data)
	default:
		return s.withTx(func(tx *sql.Tx) error { return s.upsertGenericResourceTx(tx, resourceType, id, data) })
	}
}

func (s *Store) Get(resourceType, id string) (json.RawMessage, error) {
	var data string
	err := s.db.QueryRow(
		`SELECT data FROM resources WHERE resource_type = ? AND id = ?`,
		resourceType, id,
	).Scan(&data)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

func (s *Store) List(resourceType string, limit int) ([]json.RawMessage, error) {
	if limit <= 0 {
		limit = 200
	}
	rows, err := s.db.Query(
		`SELECT data FROM resources WHERE resource_type = ? ORDER BY updated_at DESC LIMIT ?`,
		resourceType, limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []json.RawMessage
	for rows.Next() {
		var data string
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		results = append(results, json.RawMessage(data))
	}
	return results, rows.Err()
}

func (s *Store) Search(query string, limit int) ([]json.RawMessage, error) {
	if limit <= 0 {
		limit = 50
	}
	rows, err := s.db.Query(
		`SELECT r.data FROM resources r
		 JOIN resources_fts f ON r.id = f.id
		 WHERE resources_fts MATCH ?
		 ORDER BY rank
		 LIMIT ?`,
		query, limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []json.RawMessage
	for rows.Next() {
		var data string
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		results = append(results, json.RawMessage(data))
	}
	return results, rows.Err()
}

func extractObjectID(obj map[string]any) string {
	for _, key := range []string{"id", "ID", "uuid", "slug", "name"} {
		if v, ok := obj[key]; ok {
			return fmt.Sprintf("%v", v)
		}
	}
	return ""
}

func lookupFieldValue(obj map[string]any, snakeKey string) any {
	if v, ok := obj[snakeKey]; ok {
		return v
	}
	parts := strings.Split(snakeKey, "_")
	for i := 1; i < len(parts); i++ {
		if parts[i] == "" {
			continue
		}
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	if v, ok := obj[strings.Join(parts, "")]; ok {
		return v
	}
	return nil
}
func stringValue(v any) string {
	if v == nil {
		return ""
	}
	return fmt.Sprintf("%v", v)
}

func intValue(v any) int {
	switch x := v.(type) {
	case nil:
		return 0
	case bool:
		if x {
			return 1
		}
	case float64:
		return int(x)
	case int:
		return x
	case int64:
		return int(x)
	case json.Number:
		if n, err := x.Int64(); err == nil {
			return int(n)
		}
	case string:
		if n, err := strconv.Atoi(x); err == nil {
			return n
		}
	}
	return 0
}

func floatValue(v any) float64 {
	switch x := v.(type) {
	case nil:
		return 0
	case float64:
		return x
	case float32:
		return float64(x)
	case int:
		return float64(x)
	case int64:
		return float64(x)
	case json.Number:
		if n, err := x.Float64(); err == nil {
			return n
		}
	case string:
		if n, err := strconv.ParseFloat(x, 64); err == nil {
			return n
		}
	}
	return 0
}

// UpsertSubmissions inserts or updates a submissions record with domain-specific columns.
func (s *Store) UpsertSubmissions(data json.RawMessage) error {
	return s.withTx(func(tx *sql.Tx) error { return s.upsertSubmissionsTx(tx, data) })
}

func (s *Store) upsertSubmissionsTx(tx *sql.Tx, data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling submissions: %w", err)
	}
	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for submissions")
	}
	if err := s.upsertGenericResourceTx(tx, "submissions", id, data); err != nil {
		return err
	}
	_, err := tx.Exec(
		`INSERT INTO submissions (id, bounties_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET bounties_id = excluded.bounties_id, data = excluded.data, synced_at = excluded.synced_at`,
		id, stringValue(lookupFieldValue(obj, "bounties_id")), string(data), time.Now(),
	)
	return err
}

func (s *Store) UpsertLink(data json.RawMessage) error {
	return s.withTx(func(tx *sql.Tx) error { return s.upsertLinkTx(tx, data) })
}

func (s *Store) upsertLinkTx(tx *sql.Tx, data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling link: %w", err)
	}
	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for links")
	}
	if err := s.upsertGenericResourceTx(tx, "links", id, data); err != nil {
		return err
	}
	_, err := tx.Exec(`INSERT OR REPLACE INTO links
		(id, domain, key, url, short_link, title, description, archived, folder_id, clicks, leads, sales, sale_amount, last_clicked, created_at, updated_at, data, synced_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		id, stringValue(lookupFieldValue(obj, "domain")), stringValue(lookupFieldValue(obj, "key")), stringValue(lookupFieldValue(obj, "url")),
		stringValue(lookupFieldValue(obj, "short_link")), stringValue(lookupFieldValue(obj, "title")), stringValue(lookupFieldValue(obj, "description")),
		intValue(lookupFieldValue(obj, "archived")), stringValue(lookupFieldValue(obj, "folder_id")), intValue(lookupFieldValue(obj, "clicks")),
		intValue(lookupFieldValue(obj, "leads")), intValue(lookupFieldValue(obj, "sales")), floatValue(lookupFieldValue(obj, "sale_amount")),
		stringValue(lookupFieldValue(obj, "last_clicked")), stringValue(lookupFieldValue(obj, "created_at")), stringValue(lookupFieldValue(obj, "updated_at")),
		string(data), time.Now(),
	)
	return err
}

func (s *Store) UpsertEvent(data json.RawMessage) error {
	return s.withTx(func(tx *sql.Tx) error { return s.upsertEventTx(tx, data) })
}

func (s *Store) upsertEventTx(tx *sql.Tx, data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling event: %w", err)
	}
	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for events")
	}
	if err := s.upsertGenericResourceTx(tx, "events", id, data); err != nil {
		return err
	}
	eventType := stringValue(lookupFieldValue(obj, "event_type"))
	if eventType == "" {
		eventType = stringValue(lookupFieldValue(obj, "event"))
	}
	_, err := tx.Exec(`INSERT OR REPLACE INTO events
		(id, event_type, link_id, domain, url, country, city, device, browser, os, referer, timestamp, sale_amount, data, synced_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		id, eventType, stringValue(lookupFieldValue(obj, "link_id")), stringValue(lookupFieldValue(obj, "domain")),
		stringValue(lookupFieldValue(obj, "url")), stringValue(lookupFieldValue(obj, "country")), stringValue(lookupFieldValue(obj, "city")),
		stringValue(lookupFieldValue(obj, "device")), stringValue(lookupFieldValue(obj, "browser")), stringValue(lookupFieldValue(obj, "os")),
		stringValue(lookupFieldValue(obj, "referer")), stringValue(lookupFieldValue(obj, "timestamp")),
		floatValue(lookupFieldValue(obj, "sale_amount")), string(data), time.Now(),
	)
	return err
}

func (s *Store) UpsertAnalyticsSnapshot(groupBy, eventType, periodStart, periodEnd string, data json.RawMessage) error {
	_, err := s.db.Exec(
		`INSERT INTO analytics_snapshots (group_by, event_type, period_start, period_end, synced_at, data)
		 VALUES (?, ?, ?, ?, ?, ?)`,
		groupBy, eventType, periodStart, periodEnd, time.Now().UTC().Format(time.RFC3339), string(data),
	)
	return err
}

// UpsertBatch inserts or replaces multiple records in a single transaction.
// This is 10-100x faster than individual Upsert calls for bulk operations.
func (s *Store) UpsertBatch(resourceType string, items []json.RawMessage) error {
	return s.withTx(func(tx *sql.Tx) error {
		for _, item := range items {
			var obj map[string]any
			if err := json.Unmarshal(item, &obj); err != nil {
				continue
			}
			id := fmt.Sprintf("%v", lookupFieldValue(obj, "id"))
			if id == "" || id == "<nil>" {
				continue
			}
			var err error
			switch resourceType {
			case "links":
				err = s.upsertLinkTx(tx, item)
			case "events":
				err = s.upsertEventTx(tx, item)
			case "submissions":
				err = s.upsertSubmissionsTx(tx, item)
			default:
				err = s.upsertGenericResourceTx(tx, resourceType, id, item)
			}
			if err != nil {
				return fmt.Errorf("upserting %s/%s: %w", resourceType, id, err)
			}
		}
		return nil
	})
}

func (s *Store) searchFTS(table, fts, query string, limit int) ([]json.RawMessage, error) {
	if limit <= 0 {
		limit = 50
	}
	rows, err := s.db.Query(fmt.Sprintf(`SELECT t.data FROM %s t JOIN %s ON %s.rowid = t.rowid WHERE %s MATCH ? ORDER BY rank LIMIT ?`, table, fts, fts, fts), query, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []json.RawMessage
	for rows.Next() {
		var data string
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		results = append(results, json.RawMessage(data))
	}
	return results, rows.Err()
}

func (s *Store) SearchFolders(query string, limit int) ([]json.RawMessage, error) {
	return s.searchFTS("folders", "folders_fts", query, limit)
}
func (s *Store) SearchPartners(query string, limit int) ([]json.RawMessage, error) {
	return s.searchFTS("partners", "partners_fts", query, limit)
}
func (s *Store) SearchLinks(query string, limit int) ([]json.RawMessage, error) {
	return s.searchFTS("links", "links_fts", query, limit)
}

func (s *Store) SaveSyncState(resourceType, cursor string, count int) error {
	_, err := s.db.Exec(
		`INSERT INTO sync_state (resource_type, last_cursor, last_synced_at, total_count)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(resource_type) DO UPDATE SET last_cursor = excluded.last_cursor,
		 last_synced_at = excluded.last_synced_at, total_count = excluded.total_count`,
		resourceType, cursor, time.Now(), count,
	)
	return err
}

func (s *Store) GetSyncState(resourceType string) (cursor string, lastSynced time.Time, count int, err error) {
	err = s.db.QueryRow(
		`SELECT last_cursor, last_synced_at, total_count FROM sync_state WHERE resource_type = ?`,
		resourceType,
	).Scan(&cursor, &lastSynced, &count)
	if err == sql.ErrNoRows {
		return "", time.Time{}, 0, nil
	}
	return
}

// SaveSyncCursor stores the pagination cursor for a resource type.
func (s *Store) SaveSyncCursor(resourceType, cursor string) error {
	_, err := s.db.Exec(
		`INSERT INTO sync_state (resource_type, last_cursor, last_synced_at, total_count)
		 VALUES (?, ?, CURRENT_TIMESTAMP, 0)
		 ON CONFLICT(resource_type) DO UPDATE SET last_cursor = ?, last_synced_at = CURRENT_TIMESTAMP`,
		resourceType, cursor, cursor,
	)
	return err
}

// GetSyncCursor returns the last pagination cursor for a resource type.
func (s *Store) GetSyncCursor(resourceType string) string {
	var cursor sql.NullString
	s.db.QueryRow("SELECT last_cursor FROM sync_state WHERE resource_type = ?", resourceType).Scan(&cursor)
	if cursor.Valid {
		return cursor.String
	}
	return ""
}

// GetLastSyncedAt returns the last sync timestamp for a resource type.
func (s *Store) GetLastSyncedAt(resourceType string) string {
	var ts sql.NullString
	s.db.QueryRow("SELECT last_synced_at FROM sync_state WHERE resource_type = ?", resourceType).Scan(&ts)
	if ts.Valid {
		return ts.String
	}
	return ""
}

// ClearSyncCursors resets all sync state for a full resync.
func (s *Store) ClearSyncCursors() error {
	_, err := s.db.Exec("DELETE FROM sync_state")
	return err
}

// Query executes a raw SQL query and returns the rows.
// Used by workflow commands that need custom queries against the local store.
func (s *Store) Query(query string, args ...any) (*sql.Rows, error) {
	return s.db.Query(query, args...)
}

func (s *Store) Count(resourceType string) (int, error) {
	var count int
	err := s.db.QueryRow(
		`SELECT COUNT(*) FROM resources WHERE resource_type = ?`,
		resourceType,
	).Scan(&count)
	return count, err
}

func (s *Store) Status() (map[string]int, error) {
	rows, err := s.db.Query(
		`SELECT resource_type, COUNT(*) FROM resources GROUP BY resource_type ORDER BY resource_type`,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	status := make(map[string]int)
	for rows.Next() {
		var rt string
		var count int
		if err := rows.Scan(&rt, &count); err != nil {
			return nil, err
		}
		status[rt] = count
	}
	return status, rows.Err()
}
